# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db2eacd95acd27e5c871faebfd9468c0"
name = "LAB NUTRITION — Suscripciones"
application_url = "https://example.com"
embedded = true

[build]
  automatically_update_urls_on_dev = true
  include_config_on_deploy = true
  dev_store_url = "nutrition-lab-cluster.myshopify.com"

[webhooks]
  api_version = "2026-01"

[access_scopes]
  scopes = "write_orders,read_orders,read_customers,write_customers,read_products"

[auth]
  redirect_urls = [
    "https://example.com/auth/callback",
    "http://localhost:3000/auth/callback"
  ]

[pos]
  embedded = false
