api_version = "2026-01"
uid = "2b33b761-7c7d-095a-398b-daa87518ae1776af7bf7"

[[extensions]]
name = "Lab subscription activated"
type = "flow_trigger"
handle = "lab-subscription-activated"
description = "A customer activated a subscription. Send a welcome email with Shopify Email."

  [settings]

    [[settings.fields]]
    type = "customer_reference"

    [[settings.fields]]
    type = "email"
    key = "email"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "product"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "plan"
