api_version = "2026-01"
uid = "e1b71279-4deb-e2eb-f91e-a4be3696c682bac506ff"

[[extensions]]
name = "Lab subscription payment failed"
type = "flow_trigger"
handle = "lab-subscription-payment-failed"
description = "A subscription charge was rejected. Includes a payment link to recover it. Send a dunning email."

  [settings]

    [[settings.fields]]
    type = "customer_reference"

    [[settings.fields]]
    type = "email"
    key = "email"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "product"

    [[settings.fields]]
    type = "number_decimal"
    key = "amount"

    [[settings.fields]]
    type = "url"
    key = "paymentlink"
