api_version = "2026-01"
uid = "332964a4-99c1-a867-41ae-055b80361833846f8423"

[[extensions]]
name = "Lab subscription cancelled"
type = "flow_trigger"
handle = "lab-subscription-cancelled"
description = "A subscription was cancelled. Send a win-back campaign with Shopify Email."

  [settings]

    [[settings.fields]]
    type = "customer_reference"

    [[settings.fields]]
    type = "email"
    key = "email"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "product"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "reason"
